### ISSUE TITLE
Connect lightbulb to wifi?

### ISSUE THREAD

**Issue by ThracianKnight1907** [LukaJankovic/Ambience#1]
Hello,

I tried connecting my laptop to my lifx light. I connected to the bulb's own wifi and procedeed to set it up with Ambience. However I still haven't figured out how to connect the bulb to my "regular" wifi so I don't need to be permanently connected to its own network. Is this possible?

I'm using the latest flatpak

**Comment by LukaJankovic** [comment]
Hi,

I don't think the LAN api supports telling the light to change wifi. For that you would have to use the official app first, sorry!

**Comment by ThracianKnight1907** [comment]
Thanks! I used the official app to change the wifi. Ambience works nice after that.

**Comment by LukaJankovic** [comment]
Glad you like it!
