### ISSUE TITLE
1.4 freezes often is slow and has buggy light organization

### ISSUE THREAD

**Issue by Arndorferd** [LukaJankovic/Ambience#12]
1.4 is rendered almost useless due to slowness and freezing with the circle thing spinning and then stopping due to a complete freeze, it freezes almost every time rooms are switched and can take from 13 seconds to upwards of 30 seconds to switch rooms. 

Lights are showing up in rooms their not supposed to, lights are showing as both online and offline I attached a photos of the original room and then one of the room they're also in but shouldnt be in. It shows how some are offline and online

This last update is pretty non-functional

I am also having issues with lifxlan that I posted [here](https://github.com/mclarkk/lifxlan/issues/169)

I am running this on manjaro with the repository release but I also have tried the flatpak with similar results

Bedroom with same lights both online and offline
![Both offline and online](https://user-images.githubusercontent.com/41760727/153784905-b9bc987b-3beb-46ca-b9e1-146bac0652ad.png)

Kitchen that incorrectly has bedroom lights added
![Lights in wrong room](https://user-images.githubusercontent.com/41760727/153786297-95230c84-9739-471d-abdd-8640b6d51370.png)

**Comment by LukaJankovic** [comment]
I am aware that slowdowns have been happening since 1.4 and I'm working on improving those in the next version. In the next few days I'm going to upload a new version here and I would like to hear your feedback.

**Comment by LukaJankovic** [comment]
Please try [this](https://github.com/LukaJankovic/Ambience/files/8074344/io.github.lukajankovic.ambience.zip) version and report back.

It doesn't load all data before showing the lights, instead immediately shows all lights from the config. This way, all lights are presented and accessible without having to wait on a loading screen and also doesn't prevent you from accessing lights that appear offline.

I am aware of a few bugs in this version but I am just curious about the speed / general usability of the app and of course if all your lights load properly.

**Comment by Arndorferd** [comment]
It works better but there's no room control anymore for controlling all the lights in a room, could you also add a way to delete individual lights that are no longer in the manage lights menu without having to delete the whole room since theres no way to delete lights individually from the menu.

**Comment by LukaJankovic** [comment]
I will make the necessary changes and push an update soon.
