### ISSUE TITLE
Add Controlable Groups

### ISSUE THREAD

**Issue by Arndorferd** [LukaJankovic/Ambience#5]
You mention what group the light bulb is in, in the app, but I cant control groups. This makes it hard to set a room as one color and makes the app not very functional for me.

**Comment by LukaJankovic** [comment]
This feature is definitely something I've been planning to implement. However, I'm having a hard time figuring out how to integrate it nicely UI wise, so suggestions would be appreciated. Once that's figured out I'll do my best to implement it asap but I have lots to finish for my university classes over the next month so I apologize in advance if it takes some time.

**Comment by Arndorferd** [comment]
I would just do the groups similar to the way the lifx app does, have the bulbs inside the groups and allow groups to open or close when double clicked on and have the side panel adjust the whole group when the group is selected but adjust the individual bulbs when the bulbs are selected.

**Comment by Arndorferd** [comment]
Thanks for adding this!
