### ISSUE TITLE
No scroll when light list gets too long for app

### ISSUE THREAD

**Issue by Arndorferd** [LukaJankovic/Ambience#7]
There needs to be some function with a scroll bar on the side if you have too many lights in the add light section, or too many groups for them to be visable in the current frame of the program. I had too many lights in the add light section and it just went past my screen size.

**Comment by LukaJankovic** [comment]
Well that was embarrassing! I completely overlooked it when I rewrote the UI from scratch. Anyways, I fixed it now and I'll push it in an update soon
