### ISSUE TITLE
Visual Issues

### ISSUE THREAD

**Issue by Arndorferd** [LukaJankovic/Ambience#8]
The app does not seem to accept my gtk style on manjaro kde, or my qt5ct or qt6ct styles while other application do. It seemed like it did accept my qt5ct on PopOs Gnome but it was also not updated to your current version at the time.

I also would recommend for more seamless and intuitive interaction with the app that clicking on a different room/category on the left menu from what it is currently on would instead automatically bring you to that rooms main menu and close the all lights or individual lights menu if you are in one. It seems odd to me anyway to have to press the back button first to get out of the individual lights menus but still be able to change the rooms main menu "underneath" the light menu that you're currently in.

Hopefully that makes sense.

**Comment by LukaJankovic** [comment]
I fixed the behavior when moving to a different light, thank you for the feedback!

If the app is not installed as a flatpak it should follow the system theme. If you're running in flatpak however, try following the steps [here](https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html)

**Comment by Arndorferd** [comment]
For some reason trying those steps allowed me to get the application style working but without the colors?

**Comment by LukaJankovic** [comment]
Maybe you'd be better off asking in a forum such as reddit. I really can not support all theming situations etc.
